// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/8/2026, 9:29:40 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["E:/DTL/Automobile/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/DTL/Automobile/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/DTL/Automobile/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/DTL/Automobile/plugins/**/*.{js,ts,mjs}","E:/DTL/Automobile/composables/**/*.{js,ts,mjs}","E:/DTL/Automobile/utils/**/*.{js,ts,mjs}","E:/DTL/Automobile/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/DTL/Automobile/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/DTL/Automobile/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/DTL/Automobile/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;