// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/20/2026, 3:50:18 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/indipaayomal/dev/Automobile/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/indipaayomal/dev/Automobile/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/indipaayomal/dev/Automobile/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/indipaayomal/dev/Automobile/plugins/**/*.{js,ts,mjs}","/Users/indipaayomal/dev/Automobile/composables/**/*.{js,ts,mjs}","/Users/indipaayomal/dev/Automobile/utils/**/*.{js,ts,mjs}","/Users/indipaayomal/dev/Automobile/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/indipaayomal/dev/Automobile/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/indipaayomal/dev/Automobile/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/indipaayomal/dev/Automobile/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;