import type { Part } from '~/types'

export const mockParts: Part[] = [
  {
    id: 'p1',
    title: 'Genuine Toyota Electric Inverter Water Pump Assembly',
    slug: 'genuine-toyota-inverter-water-pump-zvw50-zvw30',
    partNumber: 'G9040-48020',
    oemNumber: 'G9040-52010',
    brand: 'Toyota Genuine',
    category: 'engine',
    categoryLabel: 'Engine & Hybrid System',
    price: 38500,
    originalPrice: 45000,
    condition: 'brand-new-oem',
    vehicleType: 'Car',
    compatibleVehicles: [
      {
        type: 'Car',
        make: 'Toyota',
        model: 'Prius',
        yearRange: '2015-2023',
        chassisCodes: ['ZVW50', 'ZVW51', 'ZVW52', 'ZVW55', 'ZVW30'],
      },
      {
        type: 'Car',
        make: 'Toyota',
        model: 'Aqua',
        yearRange: '2012-2021',
        chassisCodes: ['NHP10'],
      },
      {
        type: 'Car',
        make: 'Toyota',
        model: 'Corolla Axio Hybrid',
        yearRange: '2013-2022',
        chassisCodes: ['NKE165'],
      },
    ],
    chassisCodes: ['ZVW50', 'ZVW51', 'ZVW52', 'ZVW55', 'ZVW30', 'NHP10', 'NKE165'],
    inStock: true,
    stockQuantity: 14,
    warranty: '1 Year / 20,000 km Replacement Warranty',
    rating: 4.9,
    reviewCount: 38,
    images: [
      'https://images.unsplash.com/photo-1600790142055-619df03207e6?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&h=600&fit=crop&auto=format',
    ],
    description: '100% Genuine Made in Japan inverter coolant water pump. Essential replacement to prevent hybrid inverter overheating and inverter warning light check codes. Comes in original Toyota packaging with holographic seal.',
    specifications: {
      'Manufacturer': 'Toyota Motor Corporation (Aisin Japan)',
      'Voltage': '12V DC Electric',
      'Country of Origin': 'Japan',
      'Part Type': 'Hybrid Inverter Cooling Pump',
      'Fitting Position': 'Engine Bay Front Left',
    },
    seller: {
      id: 'd1',
      name: 'Prima Auto Lanka Parts Division',
      verified: true,
      location: 'Colombo 04',
      phone: '+94 11 234 5678',
      whatsapp: '+94 77 234 5678',
      rating: 4.9,
      storeId: 'd1',
    },
    featured: true,
    badge: 'OEM Genuine',
  },
  {
    id: 'p2',
    title: 'Panasonic OEM Certified Hybrid Battery Pack (Reconditioned / Cells Tested)',
    slug: 'panasonic-oem-hybrid-battery-zvw50-zvw30-nhp10',
    partNumber: 'G9510-47062',
    oemNumber: 'G9510-47060',
    brand: 'Panasonic / Toyota OEM',
    category: 'batteries',
    categoryLabel: 'Hybrid & EV Batteries',
    price: 345000,
    originalPrice: 380000,
    condition: 'reconditioned',
    vehicleType: 'Car',
    compatibleVehicles: [
      {
        type: 'Car',
        make: 'Toyota',
        model: 'Prius',
        yearRange: '2016-2022',
        chassisCodes: ['ZVW50', 'ZVW51', 'ZVW30'],
      },
      {
        type: 'Car',
        make: 'Toyota',
        model: 'Aqua',
        yearRange: '2012-2020',
        chassisCodes: ['NHP10'],
      },
    ],
    chassisCodes: ['ZVW50', 'ZVW51', 'ZVW30', 'NHP10'],
    inStock: true,
    stockQuantity: 5,
    warranty: '2 Years Comprehensive Warranty with Free Battery Health Audit',
    rating: 4.8,
    reviewCount: 29,
    images: [
      'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1600790142055-619df03207e6?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Fully re-balanced and impedance-tested NiMH hybrid battery pack featuring brand-new Panasonic Grade-A matched cells. Restores original factory fuel consumption (25+ km/L) and instant torque response.',
    specifications: {
      'Cell Chemistry': 'Nickel-Metal Hydride (Ni-MH)',
      'Nominal Voltage': '201.6V (28 Modules x 7.2V)',
      'Capacity': '6.5 Ah Tested',
      'Diagnostic Report': 'Included with individual cell IR readings',
      'Installation': 'Free installation available at Colombo showroom',
    },
    seller: {
      id: 'd6',
      name: 'EV Lanka Motors Battery Tech',
      verified: true,
      location: 'Colombo 09',
      phone: '+94 11 567 8901',
      whatsapp: '+94 77 789 0123',
      rating: 4.8,
      storeId: 'd6',
    },
    featured: true,
    badge: 'Hybrid Certified',
  },
  {
    id: 'p3',
    title: 'Akebono Japan Ceramic Ultra-Quiet Front Brake Pads Set',
    slug: 'akebono-ceramic-front-brake-pads-honda-vezel-fit',
    partNumber: 'AN-753WK',
    oemNumber: '45022-T7A-J00',
    brand: 'Akebono',
    category: 'suspension-brakes',
    categoryLabel: 'Brakes & Suspension',
    price: 16800,
    originalPrice: 19500,
    condition: 'brand-new-oem',
    vehicleType: 'SUV',
    compatibleVehicles: [
      {
        type: 'SUV',
        make: 'Honda',
        model: 'Vezel',
        yearRange: '2014-2023',
        chassisCodes: ['RU1', 'RU2', 'RU3', 'RU4', 'RV3', 'RV5'],
      },
      {
        type: 'Car',
        make: 'Honda',
        model: 'Fit',
        yearRange: '2014-2022',
        chassisCodes: ['GP5', 'GP6', 'GK3', 'GK5'],
      },
      {
        type: 'Car',
        make: 'Honda',
        model: 'Grace',
        yearRange: '2014-2020',
        chassisCodes: ['GM4', 'GM5'],
      },
      {
        type: 'Car',
        make: 'Honda',
        model: 'Civic',
        yearRange: '2016-2021',
        chassisCodes: ['FK7', 'FC1'],
      },
    ],
    chassisCodes: ['RU1', 'RU2', 'RU3', 'RU4', 'RV3', 'RV5', 'GP5', 'GP6', 'GK3', 'GK5', 'GM4', 'GM5', 'FK7', 'FC1'],
    inStock: true,
    stockQuantity: 28,
    warranty: '6 Months / 15,000 km Warranty',
    rating: 4.9,
    reviewCount: 47,
    images: [
      'https://images.unsplash.com/photo-1600790142055-619df03207e6?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Premier Akebono Pro-ACT ceramic disc brake pads engineered in Japan. Delivers maximum stopping power, zero brake squeal, and ultra-low rotor dust for Honda Vezel and Fit models.',
    specifications: {
      'Friction Material': 'Advanced Ceramic Matrix',
      'Position': 'Front Axle (Left & Right)',
      'Shim': 'Multi-layered Rubberized Anti-Squeal Shim Included',
      'Country of Origin': 'Japan',
    },
    seller: {
      id: 'd2',
      name: 'Millennium Motors Parts Outlet',
      verified: true,
      location: 'Ja-Ela, Negombo Rd',
      phone: '+94 11 345 6789',
      whatsapp: '+94 77 345 6789',
      rating: 4.7,
      storeId: 'd2',
    },
    featured: true,
    badge: 'Best Seller',
  },
  {
    id: 'p4',
    title: 'Mobil 1 Advanced Fuel Economy 0W-20 Full Synthetic Engine Oil (4 Litres)',
    slug: 'mobil-1-0w20-advanced-fuel-economy-4l',
    partNumber: 'MOB-0W20-4L',
    brand: 'Mobil 1',
    category: 'lubricants-fluids',
    categoryLabel: 'Lubricants & Fluids',
    price: 24500,
    originalPrice: 27000,
    condition: 'brand-new-oem',
    vehicleType: 'Universal',
    compatibleVehicles: [
      {
        type: 'Car',
        make: 'Toyota',
        model: 'Prius / Aqua / Corolla',
        yearRange: '2012-2024',
        chassisCodes: ['ZVW50', 'ZVW30', 'NHP10', 'NZE161', 'E210'],
      },
      {
        type: 'SUV',
        make: 'Honda',
        model: 'Vezel / CR-V / Fit',
        yearRange: '2014-2024',
        chassisCodes: ['RU3', 'RV5', 'GP5', 'RW1'],
      },
      {
        type: 'Car',
        make: 'Suzuki',
        model: 'Alto / Wagon R / Hustler',
        yearRange: '2015-2024',
        chassisCodes: ['HA36S', 'MH44S', 'MH55S', 'MR31S'],
      },
    ],
    chassisCodes: ['ZVW50', 'ZVW30', 'NHP10', 'NZE161', 'E210', 'RU3', 'RV5', 'GP5', 'RW1', 'HA36S', 'MH44S', 'MH55S', 'MR31S'],
    inStock: true,
    stockQuantity: 65,
    warranty: '100% Genuine Product Guarantee with Verification QR',
    rating: 5.0,
    reviewCount: 92,
    images: [
      'https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Mobil 1 0W-20 is an advanced full synthetic engine oil designed to help deliver outstanding engine protection and enhanced fuel economy benefits. Ideal for modern Japanese hybrid and direct-injection petrol engines.',
    specifications: {
      'Viscosity Grade': 'SAE 0W-20',
      'API Service': 'API SP / SN PLUS / SN',
      'ILSAC Rating': 'GF-6A Resource Conserving',
      'Volume': '4 Litres Bottle (Made in USA / Singapore)',
      'Recommended Drain Interval': '10,000 km or 12 months',
    },
    seller: {
      id: 'd1',
      name: 'Prima Auto Lanka Parts Division',
      verified: true,
      location: 'Colombo 04',
      phone: '+94 11 234 5678',
      whatsapp: '+94 77 234 5678',
      rating: 4.9,
      storeId: 'd1',
    },
    featured: true,
    badge: 'Popular Choice',
  },
  {
    id: 'p5',
    title: 'Castrol EDGE Titanium FST 5W-30 Full Synthetic Motor Oil (4 Litres)',
    slug: 'castrol-edge-5w30-titanium-fst-4l',
    partNumber: 'CAS-5W30-4L',
    brand: 'Castrol',
    category: 'lubricants-fluids',
    categoryLabel: 'Lubricants & Fluids',
    price: 26800,
    originalPrice: 29500,
    condition: 'brand-new-oem',
    vehicleType: 'Universal',
    compatibleVehicles: [
      {
        type: 'Car',
        make: 'BMW',
        model: '3 Series / 5 Series',
        yearRange: '2012-2024',
        chassisCodes: ['F30', 'G20', 'F10', 'G30'],
      },
      {
        type: 'Car',
        make: 'Mercedes-Benz',
        model: 'C-Class / E-Class',
        yearRange: '2014-2024',
        chassisCodes: ['W205', 'W206', 'W213'],
      },
      {
        type: 'SUV',
        make: 'Toyota',
        model: 'Land Cruiser Prado / Fortuner',
        yearRange: '2010-2024',
        chassisCodes: ['GDJ150', 'TRJ150', 'GUN156'],
      },
    ],
    chassisCodes: ['F30', 'G20', 'F10', 'G30', 'W205', 'W206', 'W213', 'GDJ150', 'TRJ150', 'GUN156', 'NZE141'],
    inStock: true,
    stockQuantity: 42,
    warranty: 'Official Castrol Importer Genuine Seal',
    rating: 4.8,
    reviewCount: 54,
    images: [
      'https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1600790142055-619df03207e6?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Castrol EDGE with Fluid TITANIUM technology transforms its structure under extreme pressure to keep metal apart and reduce friction. Recommended for European luxury turbo engines and modern common-rail diesels.',
    specifications: {
      'Viscosity Grade': 'SAE 5W-30',
      'Approvals': 'BMW Longlife-04, MB-Approval 229.51/229.52, VW 504 00/507 00',
      'API Standard': 'API SN / CF, ACEA C3',
      'Volume': '4 Litres Canister',
    },
    seller: {
      id: 'd3',
      name: 'Luxury Auto Gallery Concierge',
      verified: true,
      location: 'Colombo 03',
      phone: '+94 11 456 7890',
      whatsapp: '+94 77 456 7890',
      rating: 4.9,
      storeId: 'd3',
    },
    badge: 'European Spec',
  },
  {
    id: 'p6',
    title: 'KYB Japan Excel-G Front Gas Shock Absorbers (Pair Left & Right)',
    slug: 'kyb-excel-g-front-shock-absorbers-toyota-corolla-nze141',
    partNumber: 'KYB-339031-339032',
    oemNumber: '48510-12A50',
    brand: 'KYB (Kayaba Japan)',
    category: 'suspension-brakes',
    categoryLabel: 'Brakes & Suspension',
    price: 48500,
    originalPrice: 56000,
    condition: 'brand-new-oem',
    vehicleType: 'Car',
    compatibleVehicles: [
      {
        type: 'Car',
        make: 'Toyota',
        model: 'Corolla / Axio / Fielder',
        yearRange: '2007-2016',
        chassisCodes: ['NZE141', 'NZE144', 'ZRE142', 'ZRE144'],
      },
      {
        type: 'Car',
        make: 'Toyota',
        model: 'Premio / Allion',
        yearRange: '2007-2020',
        chassisCodes: ['NZT260', 'ZRT260', 'ZRT261'],
      },
    ],
    chassisCodes: ['NZE141', 'NZE144', 'ZRE142', 'ZRE144', 'NZT260', 'ZRT260', 'ZRT261'],
    inStock: true,
    stockQuantity: 12,
    warranty: '1 Year KYB Manufacturer Warranty',
    rating: 4.7,
    reviewCount: 31,
    images: [
      'https://images.unsplash.com/photo-1600790142055-619df03207e6?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Original KYB Excel-G twin-tube nitrogen gas pressurized struts made in Japan. Restores OEM stability, precise handling, and comfortable ride quality over Sri Lankan road conditions.',
    specifications: {
      'Design': 'Twin Tube Nitrogen Gas Charged',
      'Piston Rod': 'Triple Chrome Plated Induction Hardened',
      'Fitment': 'Direct Bolt-on OEM Replacement',
      'Quantity': 'Set of 2 Struts (Left & Right)',
    },
    seller: {
      id: 'd4',
      name: 'Island Wide Auto Kandy',
      verified: true,
      location: 'Peradeniya Road, Kandy',
      phone: '+94 81 234 5678',
      whatsapp: '+94 77 567 8901',
      rating: 4.6,
      storeId: 'd4',
    },
    badge: 'Made in Japan',
  },
  {
    id: 'p7',
    title: 'Denso Iridium TT Spark Plugs (Set of 3) - Suzuki Alto & Wagon R',
    slug: 'denso-iridium-tt-spark-plugs-suzuki-alto-wagon-r',
    partNumber: 'IXUH22I',
    oemNumber: '09482-00624',
    brand: 'Denso Japan',
    category: 'engine',
    categoryLabel: 'Engine & Ignition',
    price: 11500,
    originalPrice: 13500,
    condition: 'brand-new-oem',
    vehicleType: 'Car',
    compatibleVehicles: [
      {
        type: 'Car',
        make: 'Suzuki',
        model: 'Alto',
        yearRange: '2014-2023',
        chassisCodes: ['HA36S', 'HA36V', 'HA25S'],
      },
      {
        type: 'Car',
        make: 'Suzuki',
        model: 'Wagon R',
        yearRange: '2014-2023',
        chassisCodes: ['MH44S', 'MH55S', 'MH34S'],
      },
      {
        type: 'Car',
        make: 'Suzuki',
        model: 'Spacia / Hustler',
        yearRange: '2015-2023',
        chassisCodes: ['MK42S', 'MK53S', 'MR31S', 'MR41S'],
      },
    ],
    chassisCodes: ['HA36S', 'HA36V', 'HA25S', 'MH44S', 'MH55S', 'MH34S', 'MK42S', 'MK53S', 'MR31S', 'MR41S'],
    inStock: true,
    stockQuantity: 50,
    warranty: '50,000 km Guaranteed Ignition Life',
    rating: 4.9,
    reviewCount: 66,
    images: [
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1600790142055-619df03207e6?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Denso Twin-Tip Iridium & Platinum 0.4mm spark plugs engineered for Suzuki 660cc R06A engines. Solves idle shivering, cold start lag, and boosts fuel efficiency up to 26+ km/L.',
    specifications: {
      'Center Electrode': '0.4mm Ultra-Fine Iridium',
      'Ground Electrode': '0.7mm Platinum Needle Tip',
      'Thread Diameter': '12 mm',
      'Quantity': 'Pack of 3 Plugs',
    },
    seller: {
      id: 'd4',
      name: 'Island Wide Auto Kandy',
      verified: true,
      location: 'Peradeniya Road, Kandy',
      phone: '+94 81 234 5678',
      whatsapp: '+94 77 567 8901',
      rating: 4.6,
      storeId: 'd4',
    },
    badge: 'Fuel Saver',
  },
  {
    id: 'p8',
    title: 'Brembo UV-Coated Front Ventilated Brake Discs (Pair) - Mercedes-Benz',
    slug: 'brembo-uv-coated-brake-discs-mercedes-w205-c-class',
    partNumber: '09.C399.13',
    oemNumber: 'A0004212112',
    brand: 'Brembo Italy',
    category: 'suspension-brakes',
    categoryLabel: 'Brakes & Suspension',
    price: 84000,
    originalPrice: 96000,
    condition: 'brand-new-oem',
    vehicleType: 'Car',
    compatibleVehicles: [
      {
        type: 'Car',
        make: 'Mercedes-Benz',
        model: 'C-Class Sedan & Coupe',
        yearRange: '2014-2021',
        chassisCodes: ['W205', 'S205', 'C205', 'A205'],
      },
      {
        type: 'Car',
        make: 'Mercedes-Benz',
        model: 'E-Class',
        yearRange: '2016-2023',
        chassisCodes: ['W213', 'S213'],
      },
    ],
    chassisCodes: ['W205', 'S205', 'C205', 'A205', 'W213', 'S213'],
    inStock: true,
    stockQuantity: 8,
    warranty: '1 Year / 25,000 km Warranty',
    rating: 5.0,
    reviewCount: 19,
    images: [
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1600790142055-619df03207e6?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'High carbon Brembo ventilated disc rotors with anti-corrosion UV coating. Specifically designed for Mercedes-Benz AMG Line braking systems with drilled cooling channels.',
    specifications: {
      'Diameter': '342 mm Ventilated & Perforated',
      'Thickness': '32 mm (Minimum wear 30mm)',
      'Coating': 'UV Metallic Anti-Rust Protective Finish',
      'Country of Origin': 'Italy',
    },
    seller: {
      id: 'd3',
      name: 'Luxury Auto Gallery Concierge',
      verified: true,
      location: 'Colombo 03',
      phone: '+94 11 456 7890',
      whatsapp: '+94 77 456 7890',
      rating: 4.9,
      storeId: 'd3',
    },
    badge: 'High Performance',
  },
  {
    id: 'p9',
    title: '70mai A810 Flagship 4K HDR Dual Dashcam with Sony Starvis 2 & Built-in GPS',
    slug: '70mai-a810-4k-hdr-dual-dashcam-sony-starvis-2',
    partNumber: '70MAI-A810-KIT',
    brand: '70mai / Xiaomi Ecosystem',
    category: 'accessories',
    categoryLabel: 'Car Tech & Accessories',
    price: 49500,
    originalPrice: 58000,
    condition: 'brand-new-oem',
    vehicleType: 'Universal',
    compatibleVehicles: [
      {
        type: 'Universal',
        make: 'All Makes',
        model: 'Universal Fit (Cars, SUVs, Vans, Pickups, Trucks)',
        yearRange: '2000-2025',
        chassisCodes: ['ALL'],
      },
    ],
    chassisCodes: ['ALL', 'ZVW50', 'RU3', 'NZE141', 'W205', 'F30', 'HA36S'],
    inStock: true,
    stockQuantity: 32,
    warranty: '1 Year Complete Hardware Replacement Warranty',
    rating: 4.9,
    reviewCount: 78,
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1508974239320-0a029497e820?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'The ultimate automotive safety companion for Sri Lankan roads. Features true 4K Ultra HD front camera powered by Sony STARVIS 2 IMX678 sensor and 1080P rear camera. Built-in ADAS lane departure alerts, collision warning, 24-hour parking surveillance, and Sri Lanka GPS coordinates recording.',
    specifications: {
      'Video Resolution': '4K UHD (3840x2160) Front + 1080P HDR Rear',
      'Image Sensor': 'Sony STARVIS 2 IMX678 (Supreme Night Vision)',
      'Display': '3.0 inch IPS Screen',
      'Connectivity': 'Built-in Wi-Fi & Smartphone App (iOS / Android)',
      'Included in Box': 'Front Cam, Rear Cam, Hardwire Kit, 64GB High-Endurance MicroSD',
    },
    seller: {
      id: 'd1',
      name: 'Prima Auto Lanka Parts Division',
      verified: true,
      location: 'Colombo 04',
      phone: '+94 11 234 5678',
      whatsapp: '+94 77 234 5678',
      rating: 4.9,
      storeId: 'd1',
    },
    featured: true,
    badge: 'Top Tech 2024',
  },
  {
    id: 'p10',
    title: '7D Laser-Fitted All-Weather Luxury Floor Liners (Complete Set)',
    slug: '7d-laser-fitted-all-weather-floor-liners-toyota-prius-zvw50',
    partNumber: '7D-PRIUS-50-BLK',
    brand: 'Autocraft Premium',
    category: 'accessories',
    categoryLabel: 'Car Interior & Accessories',
    price: 28500,
    originalPrice: 34000,
    condition: 'brand-new-oem',
    vehicleType: 'Car',
    compatibleVehicles: [
      {
        type: 'Car',
        make: 'Toyota',
        model: 'Prius',
        yearRange: '2016-2023',
        chassisCodes: ['ZVW50', 'ZVW51', 'ZVW55'],
      },
    ],
    chassisCodes: ['ZVW50', 'ZVW51', 'ZVW55'],
    inStock: true,
    stockQuantity: 18,
    warranty: '2 Years Wear & Tear Material Warranty',
    rating: 4.8,
    reviewCount: 35,
    images: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1508974239320-0a029497e820?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'Precision laser-scanned 7D waterproof floor mats with deep tray design and detachable wire-loop coil layer. Shields against monsoon mud, spilled liquids, and sand while providing luxury acoustic sound dampening.',
    specifications: {
      'Material': 'High-density EVA foam + Carbon texture leatherette + Detachable PVC curly mat',
      'Fitment': 'Custom 3D scanned for Right-Hand Drive (RHD) Sri Lankan Prius ZVW50',
      'Waterproof': '100% Water, Mud & Oil Resistant',
      'Pieces': 'Front Driver, Front Passenger, Full Rear Row Bridge',
    },
    seller: {
      id: 'd1',
      name: 'Prima Auto Lanka Parts Division',
      verified: true,
      location: 'Colombo 04',
      phone: '+94 11 234 5678',
      whatsapp: '+94 77 234 5678',
      rating: 4.9,
      storeId: 'd1',
    },
    badge: 'Custom Molded',
  },
  {
    id: 'p11',
    title: 'Amaron PRO Hi-Life Maintenance-Free Automotive Battery (DIN65 / 65Ah)',
    slug: 'amaron-pro-hi-life-automotive-battery-din65',
    partNumber: 'AMR-DIN65-PRO',
    brand: 'Amaron Pro',
    category: 'batteries',
    categoryLabel: 'Automotive Batteries',
    price: 49500,
    originalPrice: 54000,
    condition: 'brand-new-oem',
    vehicleType: 'Universal',
    compatibleVehicles: [
      {
        type: 'Car',
        make: 'BMW',
        model: '3 Series',
        yearRange: '2012-2022',
        chassisCodes: ['F30', 'G20'],
      },
      {
        type: 'Car',
        make: 'Mercedes-Benz',
        model: 'C-Class',
        yearRange: '2014-2022',
        chassisCodes: ['W205'],
      },
      {
        type: 'SUV',
        make: 'Hyundai',
        model: 'Tucson / Santa Fe',
        yearRange: '2016-2023',
        chassisCodes: ['TL', 'NX4'],
      },
    ],
    chassisCodes: ['F30', 'G20', 'W205', 'TL', 'NX4'],
    inStock: true,
    stockQuantity: 24,
    warranty: '3 Years Full Replacement Warranty with Amaron Hologram Card',
    rating: 4.9,
    reviewCount: 42,
    images: [
      'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1600790142055-619df03207e6?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'High heat-resistant SilvenX alloy technology patented by Amaron. Provides incredible cranking amps and vibration resistance in Sri Lanka’s tropical climate.',
    specifications: {
      'Capacity': '65 Ah',
      'Cold Cranking Amps (CCA)': '600 CCA',
      'Technology': 'Silver-Alloy Maintenance Free Lead Acid',
      'Terminal': 'Standard DIN Terminal',
    },
    seller: {
      id: 'd3',
      name: 'Luxury Auto Gallery Concierge',
      verified: true,
      location: 'Colombo 03',
      phone: '+94 11 456 7890',
      whatsapp: '+94 77 456 7890',
      rating: 4.9,
      storeId: 'd3',
    },
    badge: '3-Year Warranty',
  },
  {
    id: 'p12',
    title: 'Michelin Primacy 4+ 215/55 R17 Premium Tyres (Set of 4)',
    slug: 'michelin-primacy-4-plus-215-55-r17-set-of-4',
    partNumber: 'MICH-2155517-P4P',
    brand: 'Michelin',
    category: 'tyres-wheels',
    categoryLabel: 'Tyres & Wheels',
    price: 215000,
    originalPrice: 236000,
    condition: 'brand-new-oem',
    vehicleType: 'Universal',
    compatibleVehicles: [
      {
        type: 'SUV',
        make: 'Honda',
        model: 'Vezel',
        yearRange: '2014-2024',
        chassisCodes: ['RU3', 'RV5'],
      },
      {
        type: 'Car',
        make: 'Toyota',
        model: 'Prius / Camry',
        yearRange: '2016-2024',
        chassisCodes: ['ZVW50', 'AXVH70'],
      },
      {
        type: 'SUV',
        make: 'Nissan',
        model: 'X-Trail',
        yearRange: '2015-2023',
        chassisCodes: ['T32'],
      },
    ],
    chassisCodes: ['RU3', 'RV5', 'ZVW50', 'AXVH70', 'T32'],
    inStock: true,
    stockQuantity: 16,
    warranty: '5 Years Manufacturer Warranty / 60,000 km Mileage Warranty',
    rating: 5.0,
    reviewCount: 38,
    images: [
      'https://images.unsplash.com/photo-1568844293986-8d0400bd4745?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1600790142055-619df03207e6?w=800&h=600&fit=crop&auto=format',
    ],
    description: 'The gold standard for luxury touring comfort and wet road braking performance. EverGrip Technology ensures safety from the first kilometer to the legal tread wear limit.',
    specifications: {
      'Size': '215/55 R17 94W',
      'Speed Rating': 'W (Up to 270 km/h)',
      'Wet Grip Grade': 'Grade A (Shortest stopping distance)',
      'Manufacture Date': 'Fresh 2024 Production DOT Batch',
    },
    seller: {
      id: 'd2',
      name: 'Millennium Motors Parts Outlet',
      verified: true,
      location: 'Ja-Ela',
      phone: '+94 11 345 6789',
      whatsapp: '+94 77 345 6789',
      rating: 4.7,
      storeId: 'd2',
    },
    badge: 'Premium Comfort',
  },
]
