import type { ServiceProvider } from '~/types'

export const mockServices: ServiceProvider[] = [
  {
    id: 's1',
    name: 'Flash Towing 24/7 Emergency Breakdown Assistance',
    slug: 'flash-towing-247-colombo',
    type: 'towing',
    typeLabel: '24/7 Emergency Towing',
    verified: true,
    rating: 4.9,
    reviewCount: 215,
    address: '88 Baseline Road, Colombo 09',
    city: 'Colombo',
    district: 'Colombo',
    province: 'Western',
    phone: '+94 11 789 2424',
    emergencyPhone: '+94 77 999 2424',
    whatsapp: '+94 77 999 2424',
    openHours: 'Open 24 Hours / 7 Days',
    is24x7: true,
    lat: 6.927,
    lng: 79.871,
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop&auto=format'],
    specializations: ['Flatbed Towing', 'Accident Recovery', 'Wheel-Lift Towing', 'Jump Start & Battery', 'Lockout & Tyre Change'],
    servicesOffered: [
      { name: 'Hydraulic Flatbed Towing (Zero-Damage)', priceEstimate: 'Rs. 7,500 base + Rs. 350/km', duration: 'Avg 20 mins arrival' },
      { name: 'Rapid Battery Jump Start & Alternator Test', priceEstimate: 'Rs. 3,500 flat', duration: '15 mins arrival' },
      { name: 'Emergency On-Site Tyre Replacement / Inflation', priceEstimate: 'Rs. 3,000 flat', duration: '20 mins arrival' },
      { name: 'Highway / Expressway Breakdown Towing', priceEstimate: 'Rs. 12,000 base + Rs. 400/km', duration: 'Immediate dispatch' },
    ],
    description: 'Western Province’s fastest 24/7 roadside emergency response fleet with 18 modern hydraulic flatbeds and rapid motor response units. Zero-scratch tow guarantee for luxury cars, hybrids, and electric vehicles.',
    features: ['24/7 Live Hotline', 'GPS Tracking of Tow Truck', 'Expressway Authorized Permit', 'Direct Insurance Billing (Ceylinco, SLIC, Allianz)'],
    towingDetails: {
      flatbed: true,
      wheelLift: true,
      heavyDuty: false,
      baseFare: 7500,
      perKmFare: 350,
      avgResponseMins: 20,
      expresswayPermit: true,
      hotline: '+94 77 999 2424',
      serviceAreas: ['Colombo 01-15', 'Dehiwala-Mount Lavinia', 'Sri Jayawardenepura Kotte', 'Gampaha', 'Southern Expressway Kadawatha to Dodangoda'],
    },
    badge: 'Fastest ETA 20 Mins',
  },
  {
    id: 's2',
    name: 'Expressway Highway Rescue 24/7',
    slug: 'expressway-highway-rescue-247',
    type: 'towing',
    typeLabel: '24/7 Highway Towing',
    verified: true,
    rating: 4.8,
    reviewCount: 148,
    address: 'Kottawa Interchange, High Level Road, Kottawa',
    city: 'Kottawa',
    district: 'Colombo',
    province: 'Western',
    phone: '+94 11 444 8899',
    emergencyPhone: '+94 71 888 2424',
    whatsapp: '+94 71 888 2424',
    openHours: 'Open 24 Hours / 365 Days',
    is24x7: true,
    lat: 6.841,
    lng: 79.967,
    images: ['https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&h=500&fit=crop&auto=format'],
    specializations: ['Southern Expressway (E01)', 'Central Expressway (E04)', 'Katunayake Expressway (E03)', 'Heavy Duty Towing'],
    servicesOffered: [
      { name: 'Expressway Breakdown Flatbed Recovery', priceEstimate: 'Rs. 9,500 base + Rs. 400/km', duration: '15-25 mins' },
      { name: 'Emergency Fuel Delivery (5L Petrol/Diesel)', priceEstimate: 'Rs. 4,500 + fuel cost', duration: '20 mins' },
      { name: 'Heavy Duty SUV / 4WD Winching & Recovery', priceEstimate: 'Rs. 15,000 base', duration: '30 mins' },
    ],
    description: 'Dedicated expressway emergency assistance units stationed permanently at Kottawa, Kadawatha, Mirigama, and Dodangoda interchanges. Full clearance for highway police and RDA protocols.',
    features: ['Highway Police Approved', 'Heavy Duty Winch Trucks', '24/7 Expressway Coverage', 'Card & QR Payment'],
    towingDetails: {
      flatbed: true,
      wheelLift: true,
      heavyDuty: true,
      baseFare: 9500,
      perKmFare: 400,
      avgResponseMins: 18,
      expresswayPermit: true,
      hotline: '+94 71 888 2424',
      serviceAreas: ['E01 Southern Expressway', 'E02 Outer Circular', 'E03 Airport Expressway', 'E04 Central Expressway'],
    },
    badge: 'Expressway Approved',
  },
  {
    id: 's3',
    name: 'Islandwide QuickRecovery Towing Service',
    slug: 'islandwide-quickrecovery-towing',
    type: 'towing',
    typeLabel: '24/7 Outstation Towing',
    verified: true,
    rating: 4.7,
    reviewCount: 96,
    address: '15 William Gopallawa Mawatha, Kandy',
    city: 'Kandy',
    district: 'Kandy',
    province: 'Central',
    phone: '+94 81 222 9900',
    emergencyPhone: '+94 76 555 8899',
    whatsapp: '+94 76 555 8899',
    openHours: 'Open 24 Hours',
    is24x7: true,
    lat: 7.285,
    lng: 80.628,
    images: ['https://images.unsplash.com/photo-1568844293986-8d0400bd4745?w=800&h=500&fit=crop&auto=format'],
    specializations: ['Hill Country Recovery', 'Inter-Province Long Distance Towing', 'Accident Haulage'],
    servicesOffered: [
      { name: 'Long-Distance Vehicle Transport (Inter-city)', priceEstimate: 'Rs. 300/km fixed', duration: 'Scheduled / Emergency' },
      { name: 'Kandy / Nuwara Eliya Mountain Recovery', priceEstimate: 'Rs. 12,500 base', duration: '25 mins' },
    ],
    description: 'Central Province and islandwide long-distance transport specialists. Equipped for steep inclines, hairpins, and outstation breakdown recovery back to Colombo.',
    features: ['Outstation Fleet', 'Full Transit Cargo Insurance', 'Flatbed Trucks'],
    towingDetails: {
      flatbed: true,
      wheelLift: false,
      heavyDuty: true,
      baseFare: 8000,
      perKmFare: 300,
      avgResponseMins: 25,
      expresswayPermit: true,
      hotline: '+94 76 555 8899',
      serviceAreas: ['Kandy', 'Matale', 'Kurunegala', 'Nuwara Eliya', 'Kegalle'],
    },
    badge: 'Hill Country Specialist',
  },
  {
    id: 's4',
    name: 'Hybrid Hub Sri Lanka (High Voltage Battery & Inverter Lab)',
    slug: 'hybrid-hub-sri-lanka-colombo',
    type: 'garage',
    typeLabel: 'Specialized Hybrid/EV Workshop',
    verified: true,
    rating: 4.9,
    reviewCount: 312,
    address: '425 Nawala Road, Rajagiriya',
    city: 'Rajagiriya',
    district: 'Colombo',
    province: 'Western',
    phone: '+94 11 288 7766',
    whatsapp: '+94 77 444 3322',
    openHours: 'Mon - Sat: 8:00 AM - 6:00 PM',
    is24x7: false,
    lat: 6.898,
    lng: 79.897,
    images: ['https://images.unsplash.com/photo-1600790142055-619df03207e6?w=800&h=500&fit=crop&auto=format'],
    specializations: ['Hybrid Battery Rebuild & Balancing', 'Inverter Diagnostics', 'ABS Actuator Repair', 'Toyota / Honda / Nissan Hybrid', 'EV Diagnostics'],
    servicesOffered: [
      { name: 'Comprehensive 40-Point Hybrid System & Battery Health Test', priceEstimate: 'Rs. 4,500', duration: '45 mins' },
      { name: 'Hybrid Battery Cell Rebalancing & Deep Conditioning', priceEstimate: 'Rs. 35,000', duration: '1 day' },
      { name: 'Inverter Coolant Flush & Pump Replacement', priceEstimate: 'Rs. 12,000 + parts', duration: '2 hours' },
      { name: 'ABS Brake Actuator Overhaul & Programming', priceEstimate: 'Rs. 45,000', duration: '1 day' },
    ],
    description: 'Sri Lanka’s pioneer specialized hybrid center equipped with factory diagnostic tools (Toyota Techstream, Honda HDS). Certified by hybrid powertrain engineers with over 10,000 successful battery restorations.',
    features: ['Free Diagnostic Scan with Any Service', 'Genuine Panasonic / OEM Cells Only', '6-Month to 2-Year Warranty on Repairs', 'Air-Conditioned Customer Lounge with Wi-Fi'],
    badge: 'Top Rated Hybrid Lab',
  },
  {
    id: 's5',
    name: 'German Tech Masters (BMW, Mercedes-Benz, Audi Specialists)',
    slug: 'german-tech-masters-colombo',
    type: 'garage',
    typeLabel: 'European Luxury Workshop',
    verified: true,
    rating: 4.8,
    reviewCount: 184,
    address: '312 High Level Road, Nugegoda',
    city: 'Nugegoda',
    district: 'Colombo',
    province: 'Western',
    phone: '+94 11 555 4321',
    whatsapp: '+94 77 888 1212',
    openHours: 'Mon - Sat: 8:30 AM - 6:30 PM',
    is24x7: false,
    lat: 6.872,
    lng: 79.895,
    images: ['https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&h=500&fit=crop&auto=format'],
    specializations: ['BMW M Series', 'Mercedes-Benz AMG', 'Audi S-Line', 'ZF Transmission Overhaul', 'Air Suspension Calibrations', 'ECU Tuning'],
    servicesOffered: [
      { name: 'Complete European Computer Diagnostics & Fault Coding', priceEstimate: 'Rs. 6,500', duration: '1 hour' },
      { name: 'ZF 8-Speed Automatic Transmission Service & Adaptation', priceEstimate: 'Rs. 65,000 + fluid', duration: '4 hours' },
      { name: 'Air Suspension Air Strut & Compressor Overhaul', priceEstimate: 'Rs. 75,000+', duration: '1 day' },
    ],
    description: 'Specialized facility exclusively dedicated to German vehicles. Equipped with original BMW ISTA+, Mercedes Xentry, and VAG-COM diagnostics. Certified master technicians with dealership background.',
    features: ['Original Factory Software', 'OEM European Parts in Stock', 'Warranty on All Mechanical Work'],
    badge: 'German Auto Certified',
  },
  {
    id: 's6',
    name: 'Colombo Auto Works & Engine Rebuild Lab',
    slug: 'colombo-auto-works',
    type: 'garage',
    typeLabel: 'Complete Auto Repair Workshop',
    verified: true,
    rating: 4.7,
    reviewCount: 165,
    address: '74 Havelock Road, Colombo 05',
    city: 'Colombo',
    district: 'Colombo',
    province: 'Western',
    phone: '+94 11 258 9012',
    whatsapp: '+94 77 333 4455',
    openHours: 'Mon - Sat: 8:00 AM - 6:00 PM',
    is24x7: false,
    lat: 6.883,
    lng: 79.865,
    images: ['https://images.unsplash.com/photo-1600790142055-619df03207e6?w=800&h=500&fit=crop&auto=format'],
    specializations: ['Engine Overhaul', 'Gearbox Repair', 'Brake Lathe Disc Resurfacing', 'AC & Climate Control', 'Suspension Bushings'],
    servicesOffered: [
      { name: 'Full Mechanical Inspection & Compression Test', priceEstimate: 'Rs. 5,000', duration: '2 hours' },
      { name: 'On-Car Brake Disc Rotor Skimming / Lathe', priceEstimate: 'Rs. 4,500 per pair', duration: '1.5 hours' },
      { name: 'Complete Automotive AC Gas Evacuation & Leak Test', priceEstimate: 'Rs. 8,500', duration: '2 hours' },
    ],
    description: 'Trusted multi-brand automotive repair facility with over 25 years of family engineering legacy in Colombo. Hydraulic lifts, disc skimming, cylinder head resurfacing, and complete mechanical overhauls.',
    features: ['In-house Machine Shop', 'All Vehicle Brands', 'Detailed Video Progress Updates on WhatsApp'],
    badge: '25 Years Experience',
  },
  {
    id: 's7',
    name: 'Laugfs Car Care Super Service Station',
    slug: 'laugfs-car-care-super-center-havelock',
    type: 'service-station',
    typeLabel: 'Service Station & Lube Bay',
    verified: true,
    rating: 4.8,
    reviewCount: 290,
    address: '180 Havelock Road, Colombo 05',
    city: 'Colombo',
    district: 'Colombo',
    province: 'Western',
    phone: '+94 11 441 5566',
    whatsapp: '+94 77 666 7788',
    openHours: 'Mon - Sun: 7:00 AM - 8:00 PM',
    is24x7: false,
    lat: 6.879,
    lng: 79.868,
    images: ['https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?w=800&h=500&fit=crop&auto=format'],
    specializations: ['Express Lube Maintenance', 'Under-Chassis Wash & Rust Treatment', 'Touchless Automatic Wash', 'Engine Bay Detailing'],
    servicesOffered: [
      { name: 'Express Full Periodic Lube Service (Labor + 25-point check)', priceEstimate: 'Rs. 4,500 + oil/filter', duration: '45 mins' },
      { name: 'Underbody Wash, Degreasing & Anti-Rust Graphite Spray', priceEstimate: 'Rs. 5,500', duration: '1 hour' },
      { name: 'Deluxe Body Wash, Vacuum & Interior Dashboard Conditioning', priceEstimate: 'Rs. 3,500', duration: '40 mins' },
    ],
    description: 'State-of-the-art service station equipped with automated underbody spray bays, quick lube pits, and premium motor oils (Mobil 1, Castrol, Valvoline). Quick turnaround with comfortable air-conditioned waiting café.',
    features: ['Coffee Lounge & Free High-Speed Wi-Fi', 'Express 45-Min Lube Service', 'Genuine Oil Guarantee'],
    badge: 'Express Service Bay',
  },
  {
    id: 's8',
    name: 'Auto Miraj Grand Express & Ceramic Detailing Center',
    slug: 'auto-miraj-grand-express-rajagiriya',
    type: 'service-station',
    typeLabel: 'Service Station & Detailing Studio',
    verified: true,
    rating: 4.9,
    reviewCount: 420,
    address: '55 Kotte Road, Rajagiriya',
    city: 'Rajagiriya',
    district: 'Colombo',
    province: 'Western',
    phone: '+94 11 777 2200',
    whatsapp: '+94 77 222 1100',
    openHours: 'Mon - Sun: 7:30 AM - 7:30 PM',
    is24x7: false,
    lat: 6.902,
    lng: 79.892,
    images: ['https://images.unsplash.com/photo-1601362840469-51e4d8d58785?w=800&h=500&fit=crop&auto=format'],
    specializations: ['9H Ceramic Coating', 'Interior Steam Sterilization', 'Cut & Polish', 'Windshield Water Repellent', 'Leather Rejuvenation'],
    servicesOffered: [
      { name: '3-Stage Paint Correction & High-Gloss Machine Polish', priceEstimate: 'Rs. 18,500', duration: '1 day' },
      { name: 'Permanent 9H Nano Ceramic Coating (3-Year Warranty)', priceEstimate: 'Rs. 65,000', duration: '2 days' },
      { name: 'Deep Interior Steam Clean, Carpet Extraction & AC Odor Neutralizer', priceEstimate: 'Rs. 14,000', duration: '5 hours' },
    ],
    description: 'Sri Lanka’s leading auto care and detailing chain. Dust-free temperature controlled ceramic coating booth, computerized paint thickness meters, and certified Rupes detailing master technicians.',
    features: ['Dust-Free Detailing Studio', '3-Year Warranty Card on Coatings', 'Card / Koko 3-Month Installments'],
    badge: '9H Ceramic Certified',
  },
]
